#:kivy 1.0.9

<SimulationBall>:
    canvas:
        Ellipse:
            pos: [self.pos[0] - self.radius, self.pos[1] - self.radius]
            size: self.radius*2, self.radius*2

<SimulationBlock>:
    canvas:
        Rectangle:
            pos: [self.pos[0] - self.size[0]/2, self.pos[1] - self.size[1]/2]
            size: self.size
        #Rotate:
        #    angle: self.theta
        #    axis: (0,0,1)